# TEST
variables:
  SCHEDULER_PARAMETERS: "-n 1 -p nitrogen"
  USER: legit


stages:
    - build
    - unittest
    - autodoc
    - deploy
    - cleanup

before_script:
        - hostname

######################
#### IMAGE BUILDS #########################################################
######################

build-docker-test-image:
    tags:
       - local
       - shell
    stage: build
    script:
       - docker build --no-cache -t lv_unittest -f Dockerfile .


build-docker-autodoc-image:
    tags:
       - local
       - shell
    stage: build
    script:
       - docker build --no-cache -t lv_sphinxdoc -f doc/Dockerfile . 


#### UNITTESTS ####


unittest-Molecule:
    tags:
        - local
        - shell
    stage: unittest
    needs: [build-docker-test-image]
    script:
        - docker run --workdir /app/tests lv_unittest pytest -v test_Molecule.py


unittest-Modes:
    tags:
        - local
        - shell
    stage: unittest
    needs: [build-docker-test-image]
    script:
        - docker run --workdir /app/tests lv_unittest pytest -v test_Modes.py


unittest-LocVib:
    tags:
        - local
        - shell
    stage: unittest
    needs: [build-docker-test-image] #,unittest-Modes]
    script:
        - docker run --workdir /app/tests lv_unittest pytest -v test_LocVib.py


unittest-HugAnalysis:
    tags:
        - local
        - shell
    stage: unittest
    needs: [build-docker-test-image] #, unittest-Modes]
    script:
        - docker run --workdir /app/tests lv_unittest pytest -v test_HugAnalysis.py


unittest-Spectrum:
    tags:
        - local
        - shell
    stage: unittest
    needs: [build-docker-test-image,unittest-Modes]
    script:
        - docker run --workdir /app/tests lv_unittest pytest -v test_Spectrum.py


unittest-Results:
    tags:
        - local
        - shell
    stage: unittest
    needs: [build-docker-test-image,unittest-Molecule]
    script:
        - docker run --workdir /app/tests lv_unittest pytest -v test_Results.py

# Interfaces ---------

unittest-PySNF:
    tags:
        - local
        - shell
    stage: unittest
    needs:
        - build-docker-test-image
        - unittest-Modes
        - unittest-Molecule
        - unittest-Results
    script:
        - docker run --workdir /app/tests lv_unittest pytest -v test_PySNF.py

#######################
#### DOCUMENTATION #############################################################
#######################

unittest-Coverage:
    tags:
        - local
        - shell
    stage: autodoc
    needs:
        - build-docker-test-image
    script:
        - docker run --workdir /app/tests --name lv_test_coverage lv_unittest pytest --cov=VibTools --cov-report term --cov-report xml:coverage.xml
        - docker cp lv_test_coverage:/app/tests/coverage.xml coverage.xml
    coverage: '/(?i)total.*? (100(?:\.0+)?\%|[1-9]?\d(?:\.\d+)?\%)$/'
    artifacts:
      reports:
        coverage_report:
          coverage_format: cobertura
          path: coverage.xml


build-sphinx-doc:
    tags:
        - local
        - shell
    stage: autodoc
    needs: [build-docker-autodoc-image, unittest-Coverage]
    script:
        - docker run --workdir /app/doc --name sphinxdoc_lv_container lv_sphinxdoc sphinx-build . build 

pages:
    tags:
        - local
        - shell
    stage: deploy
    needs: [build-sphinx-doc]
    script:
        - docker cp sphinxdoc_lv_container:/app/doc/build/. public/ 
    artifacts:
        paths:
         - public

################################################
#alternative installation/environment via Conda#
################################################

build-docker-conda-test-image:
    tags:
       - local
       - shell
    stage: build
    script:
       - docker build --no-cache -t lv_condock -f tests/Dockerfile .


unittest-Conda-Env-all_tests:
    tags:
        - local
        - shell
    stage: unittest
    needs: 
        - build-docker-conda-test-image
    script:
        - docker run --workdir /app/tests lv_condock conda run -n VibToolsCondaENV pytest -v

##################
#### CLEAN UP ##################################################################
##################

cleanup-docker:
    stage: cleanup
    tags: [local, shell]
    needs:
        - build-docker-test-image
        - build-docker-autodoc-image
        - build-docker-conda-test-image
        - unittest-Molecule
        - unittest-Modes
        - unittest-PySNF
        - unittest-LocVib
        - unittest-HugAnalysis
        - unittest-Spectrum
        - unittest-Results
        - unittest-Conda-Env-all_tests
        - build-sphinx-doc
        - unittest-Coverage 
    script:
        - docker rmi -f lv_condock:latest
        - docker rmi -f lv_sphinxdoc:latest
        - docker rmi -f lv_unittest:latest
        - docker rm $(docker ps --filter status=exited -q)
        - docker system df
    when: always
