variables:
  SCHEDULER_PARAMETERS: "-n 1 -p nitrogen"
  USER: legit
  LOCVIBHOME: $CI_BUILDS_DIR/$CI_PROJECT_PATH


stages:
    - build
    - test
    - deploy


before_script:
        - hostname
        - module load module_include_dir
        - . /usr/share/modules/init/bash
        - . /usr/share/modules/init/setup
        - export PYTHONPATH=$PYTHONPATH:$LOCVIBHOME/src
        - module load python/anaconda3-2021.11
        - source activate base
        - conda init bash
        - conda env list
        - conda list


build-requirements:
    tags:
        - nodes
    stage: build
    script:
        - cd requirements/
        - conda env create -f environment_human_readable.yml --force # create conda env from human readable requirements
        -  cd ../
        - conda activate VThr #VT_CI: maschine readable VibTools conda CI-environment
        - conda env list # Show some environment details for debugging
        - conda list
        - conda list -n VThr python
        - conda list -n VThr matplotlib
        - conda list -n VThr numpy     
        - conda list -n VThr scipy
        - conda list -n VThr openbabel
        - conda list -n VThr pytest
        - conda list -n VThr sphinx
        - conda list -n VThr sphinx_rtd_theme


unittest-Molecule:
    tags:
        - nodes
    stage: test
    script:
        - conda activate VThr
        - cd tests/
        - pytest -v test_Molecule.py
        - cd ../


unittest-Modes:
    tags:
        - nodes
    stage: test
    script:
        - conda activate VThr
        - cd tests/
        - pytest -v test_Modes.py
        - cd ../


unittest-PySNF:
    tags:
        - nodes
    stage: test
    script:
        - conda activate VThr
        - cd tests/
        - pytest -v test_PySNF.py
        - cd ../


unittest-LocVib:
    tags:
        - nodes
    stage: test
    script:
        - conda activate VThr
        - cd tests/
        - pytest -v test_LocVib.py
        - cd ../

unittest-HugAnalysis:
    tags:
        - nodes
    stage: test
    script:
        - conda activate VThr
        - cd tests/
        - pytest -v test_HugAnalysis.py
        - cd ../

unittest-Spectrum:
    tags:
        - nodes
    stage: test
    script:
        - conda activate VThr
        - cd tests/
        - pytest -v test_Spectrum.py
        - cd ../


test-sphinx-doc:
    tags:
        - nodes
    stage: test
    script:
        - conda activate VT_CI # The VThr environment does not yet work for the Sphinx Doc
        - cd doc/
        - mkdir _build
        - sphinx-build . _build/
        - cd ../


pages:
     tags: 
        - local
     stage: deploy
     script:
        - conda activate VT_CI
        - python setup.py install
        - cd doc/
        - sphinx-build -b html . ../public
        - cd ../../
     artifacts:
        paths:
            - public



