variables:
  SCHEDULER_PARAMETERS: "-n 1 -p nitrogen"
  USER: legit


stages:
    - build
    - unittest
    - autodoc
    - deploy
    - cleanup

before_script:
        - hostname

#### IMAGE BUILDS ####


build-docker-test-image:
    tags:
       - local
       - shell
    stage: build
    script:
       - docker build --no-cache -t lv_unittest -f Dockerfile.unittests .


build-docker-autodoc-image:
    tags:
       - local
       - shell
    stage: build
    script:
       - docker build --no-cache -t lv_sphinxdoc -f Dockerfile.sphinx_doc . 


#### UNITTESTS ####


unittest-Molecule:
    tags:
        - local
        - shell
    stage: unittest
    needs: [build-docker-test-image]
    script:
        - docker run --workdir /app/tests lv_unittest pytest -v test_Molecule.py


unittest-Modes:
    tags:
        - local
        - shell
    stage: unittest
    needs: [build-docker-test-image]
    script:
        - docker run --workdir /app/tests lv_unittest pytest -v test_Modes.py


unittest-PySNF:
    tags:
        - local
        - shell
    stage: unittest
    needs: [build-docker-test-image]
    script:
        - docker run --workdir /app/tests lv_unittest pytest -v test_PySNF.py


unittest-LocVib:
    tags:
        - local
        - shell
    stage: unittest
    needs: [build-docker-test-image]
    script:
        - docker run --workdir /app/tests lv_unittest pytest -v test_LocVib.py


unittest-HugAnalysis:
    tags:
        - local
        - shell
    stage: unittest
    needs: [build-docker-test-image]
    script:
        - docker run --workdir /app/tests lv_unittest pytest -v test_HugAnalysis.py


unittest-Spectrum:
    tags:
        - local
        - shell
    stage: unittest
    needs: [build-docker-test-image]
    script:
        - docker run --workdir /app/tests lv_unittest pytest -v test_Spectrum.py


#### DOCUMENTATION ####


build-sphinx-doc:
    tags:
        - local
        - shell
    stage: autodoc
    needs: [build-docker-autodoc-image ]
    script:
        - docker run --workdir /app/doc --name sphinxdoc_lv_container lv_sphinxdoc sphinx-build . build 


pages:
    tags:
        - local
        - shell
    stage: deploy
    needs: [build-sphinx-doc]
    script:
        - docker cp sphinxdoc_lv_container:/app/doc/build/. public/ 
    artifacts:
        paths:
         - public


#### CLEAN UP ####

cleanup-docker:
    stage: cleanup
    tags: [local, shell]
    needs:
        - build-docker-test-image
        - build-docker-autodoc-image
        - unittest-Molecule
        - unittest-Modes
        - unittest-PySNF
        - unittest-LocVib
        - unittest-HugAnalysis
        - unittest-Spectrum
        - build-sphinx-doc
        - pages
    script:
        - docker rmi -f lv_sphinxdoc:latest
        - docker rmi -f lv_unittest:latest
        - docker rm $(docker ps --filter status=exited -q)
        - docker system df
    when: always
