name: VThr
channels:
  - conda-forge
  - defaults
dependencies:
  - python==3.11.0
  - numpy==1.23.4
  - matplotlib==3.6.1
  - openbabel==3.1.1
  - pytest==7.2.0
  - sphinx==5.3.0
  - sphinx_rtd_theme==0.4.3
